import type { HrUser, OnboardingSubmission } from '../types/database';

export const DEMO_HR_USER: HrUser = {
  id: 'demo-hr-id',
  email: 'demo@demo.com',
  full_name: 'Demo HR Yöneticisi',
  role: 'admin',
  created_at: new Date().toISOString(),
};

export const DEMO_SUBMISSIONS: OnboardingSubmission[] = [
  {
    id: 'demo-sub-1',
    employee_id: 'demo-emp-1',
    status: 'submitted',
    current_step: 6,
    digital_consent: true,
    submitted_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    personal_info: {
      full_name: 'Ahmet Yılmaz',
      tc_no: '12345678901',
      birth_date: '1990-05-15',
      birth_place: 'İstanbul',
      gender: 'male',
      marital_status: 'married',
      education_level: 'lisans',
      department: 'Yazılım',
      job_title: 'Frontend Geliştirici',
      start_date: '2024-02-01',
    },
    contact_info: {
      phone: '05551234567',
      address: 'Bağcılar Mah. Örnek Sok. No:5 D:3',
      city: 'İstanbul',
      district: 'Bağcılar',
      postal_code: '34200',
    },
    emergency_contact: { name: 'Ayşe Yılmaz', relationship: 'Eş', phone: '05559876543' },
    bank_info: { bank_name: 'Ziraat Bankası', iban: 'TR330006100519786457841326', account_holder: 'Ahmet Yılmaz' },
    employees: { id: 'demo-emp-1', email: 'ahmet@sirket.com', full_name: 'Ahmet Yılmaz', phone: '05551234567', token: 'demo-token-1', invited_by: null, token_used: true, created_at: new Date().toISOString() },
    documents: [],
    approval_logs: [],
  },
  {
    id: 'demo-sub-2',
    employee_id: 'demo-emp-2',
    status: 'approved',
    current_step: 6,
    digital_consent: true,
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    personal_info: {
      full_name: 'Fatma Kaya',
      tc_no: '98765432109',
      birth_date: '1995-08-22',
      birth_place: 'Ankara',
      gender: 'female',
      marital_status: 'single',
      education_level: 'yukseklisans',
      department: 'İnsan Kaynakları',
      job_title: 'İK Uzmanı',
      start_date: '2024-01-15',
    },
    contact_info: { phone: '05441234567', address: 'Çankaya Mah. Atatürk Cad. No:10', city: 'Ankara', district: 'Çankaya', postal_code: '06100' },
    emergency_contact: { name: 'Mehmet Kaya', relationship: 'Baba', phone: '05329876543' },
    bank_info: { bank_name: 'Garanti BBVA', iban: 'TR320006200119000006672315', account_holder: 'Fatma Kaya' },
    employees: { id: 'demo-emp-2', email: 'fatma@sirket.com', full_name: 'Fatma Kaya', phone: '05441234567', token: 'demo-token-2', invited_by: null, token_used: true, created_at: new Date().toISOString() },
    documents: [],
    approval_logs: [],
  },
  {
    id: 'demo-sub-3',
    employee_id: 'demo-emp-3',
    status: 'draft',
    current_step: 3,
    digital_consent: false,
    submitted_at: null,
    updated_at: new Date().toISOString(),
    personal_info: {
      full_name: 'Can Demir',
      tc_no: '11223344556',
      birth_date: '1998-12-01',
      birth_place: 'İzmir',
      gender: 'male',
      marital_status: 'single',
      education_level: 'lisans',
      department: 'Pazarlama',
      job_title: 'Pazarlama Uzmanı',
      start_date: '2024-03-01',
    },
    contact_info: null,
    emergency_contact: null,
    bank_info: null,
    employees: { id: 'demo-emp-3', email: 'can@sirket.com', full_name: 'Can Demir', phone: null, token: 'demo-token-3', invited_by: null, token_used: false, created_at: new Date().toISOString() },
    documents: [],
    approval_logs: [],
  },
];
